User/urls.py
from django.urls import path

from User import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('homesuper/', views.home_super, name='home_super'),

    path('mine/', views.mine, name='mine'),
    path('minesuper/', views.mine_super, name='mine_super'),
    path('delete/', views.delete, name='delete'),
    path('addition/', views.addition, name='addition'),
    path('search/', views.search, name='search'),
    path('update/', views.update, name='update'),

    path('checkuser/', views.check_user, name='check_user'),
    path('activate/', views.activate, name='activate'),
    path('activatesuper/', views.activate_super, name='activate_super'),
    path('register/', views.register, name='register'),

    # 验证码
    path('getcode/', views.get_code, name='get_code'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

Vehicle/urls.py
from django.urls import path

from Vehicle import views

urlpatterns = [
    path('index/', views.index, name='index'),

    path('search/', views.search, name='search'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('add/', views.add, name='add'),
    path('checkplate/', views.check_plate, name='check_plate'),

    path('addroad/', views.add_road, name='add_road'),
    path('updateroad/', views.update_road, name='update_road'),
    path('saveroad/', views.save_road, name='save_road'),
    path('deleteroad/', views.delete_road, name='delete_road'),
    path('predict/', views.predict, name='predict'),
]

djangoGraduationProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('User.urls', 'user'), namespace='user')),
    path('vehicle/', include(('Vehicle.urls', 'vehicle'), namespace='vehicle')),
]

templates/main/mine.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/main/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--我的</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine' %}">mine</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <div id="mine">
        <div class="fixed">
            <span>
                {% if is_login %}
                    <img class="u_icon" src="{{ icon }}" alt="{{ username }}">
                {% else %}
                    <span class="glyphicon glyphicon-user"></span>
                {% endif %}
            </span>
            {% if is_login %}
                <p>欢迎您，{{ username }}!</p>
                <br>
                <a href="{% url 'user:update' %}?user_id={{ user_id }}">修改个人信息<span class="glyphicon glyphicon-check"></a>
            {% else %}
                <a href="{% url 'user:login' %}"> 登录<span class="glyphicon glyphicon-log-in"></span></a>
                <br>
            {% endif %}

            {% if not is_login %}
                <a href="{% url 'user:register' %}">注册<span class="glyphicon glyphicon-registration-mark"></span></a>
            {% endif %}
        </div>
        <div>
            {% if is_login %}
                <p>
                    <a href="{% url 'user:logout' %}">退出当前账号<span class="glyphicon glyphicon-log-out"></span></a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/main/mine_super.html
{% extends 'main/mine.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/main/css/mine_super.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/main/js/mine_super.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--我的(管理员)</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine_super' %}">mine_super</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    {{ block.super }}
    {% if is_login %}
        <div align="center">
            <label for="search" class="control-label">查找用户：</label>
            <input id="search" type="text" placeholder="请输入用户名查找">
            {#         <a href="{% url 'user:' %}">查找</a>#}
            <button onclick="search()" class="btn btn-default">查找</button>
        </div>

        <table border="1" class="table table-hover">
            <tr class="active">
                <td>姓名</td>
                <td>邮箱</td>
                <td>是否是管理员</td>
            </tr>
            {% for user in page_object.object_list %}
                {#            未删除的显示出来#}
                {#                {% ifequal user.is_delete False %}#}
                <tr>
                    <td>{{ user.u_username }}</td>
                    <td>{{ user.u_email }}</td>
                    {% ifequal user.is_super True %}
                        <td>是</td>
                    {% else %}
                        <td>否</td>
                    {% endifequal %}
                </tr>
                {#                {% endifequal %}#}
            {% endfor %}
        </table>

        {#    分页器#}
        <div align="center">
            <nav aria-label="Page navigation">
                <ul class="pagination pagination-lg">
                    {% if page_object.has_previous %}
                        <li>
                            <a href="{% url 'user:mine_super' %}?page={{ page_object.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_index in page_range %}
                        {% ifequal page_index page_object.number %}
                            <li class="active"><a
                                    href="{% url 'user:mine_super' %}?page={{ page_index }}">{{ page_index }}</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'user:mine_super' %}?page={{ page_index }}">{{ page_index }}</a></li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_object.has_next %}
                        <li>
                            <a href="{% url 'user:mine_super' %}?page={{ page_object.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    {% endif %}
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'user:home_super' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-th-large"></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'vehicle:index' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-road"></span>
                </dt>
                <dd>车辆</dd>
            </dl>
        </a>
        <a href="{% url 'user:mine_super' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-home"></span>
                </dt>
                <dd>管理用户</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

templates/main/super_index.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--首页(管理员)</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:home_super' %}">super_index</a></li>
        </ul>
    </header>
{% endblock %}
{% block content %}
    <div id="content">

    <div align="center" class="content">
        <p>南昌大学 软件学院 </p>
        <p>基于深度学习的车辆识别系统</p>
        <p>指导老师：饶泓教授</p>
        <p>学生：王强</p>
        <p>当前位置：管理员首页</p>
    </div>
    </div>
{% endblock %}

{% block footer %}
    {{ block.super }}
    <footer>
        <a href="{% url 'user:home_super' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-th-large"></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'vehicle:index' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-road"></span>
                </dt>
                <dd>车辆</dd>
            </dl>
        </a>
        <a href="{% url 'user:mine_super' %}">
            <dl>
                <dt>
                    <span class="glyphicon glyphicon-home"></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
        </dl>
    </footer>
{% endblock %}

templates/main/vehicle_index.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/vehicle/css/index.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--车牌识别主页</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:search' %}" method="get">
        {% ifequal user.is_super True %}
            <div id="vehicle">
                <div class="fixed">
                    {#                添加主体#}
                    <a href="{% url 'vehicle:add' %}">添加车辆<span class="glyphicon glyphicon-plus-sign"></span></a>
                    <br>
                    <a href="{% url 'vehicle:add_road' %}">添加道路<span class="glyphicon glyphicon-plus-sign"></span></a>
                    <br>
                    <a href="{% url 'vehicle:update_road' %}">修改道路<span
                            class="glyphicon glyphicon-circle-arrow-up"></span></a>
                </div>
            </div>
        {% endifequal %}

        <div align="center">
            <label for="search" class="control-label">查找用户：</label>
            <input id="search" type="text" placeholder="请输入用户名查找" name="username">
            <button type="submit" class="btn btn-default">查找</button>
        </div>

        <table border="1" class="table table-hover">
            <tr class="active">
                <td>姓名</td>
                <td>车牌</td>
                <td>道路</td>
                <td>时间</td>
                <td>是否违规</td>
            </tr>
            {% for plate in page_object.object_list %}
                {#            未删除的显示出来#}
                {% ifequal plate.p_is_delete False %}
                    <tr>
                        <td>{{ plate.p_username.u_username }}</td>
                        <td>{{ plate.p_plate }}</td>
                        <td>{{ plate.p_roads.r_name }}</td>
                        <td>{{ plate.p_time }}</td>
                        {% ifequal plate.p_against False %}
                            <td>未违规</td>
                        {% else %}
                            <td>违规</td>
                        {% endifequal %}
                    </tr>
                {% endifequal %}
            {% endfor %}
        </table>

        {#    分页器#}
        <div align="center">
            <nav aria-label="Page navigation">
                <ul class="pagination pagination-lg">
                    {% if page_object.has_previous %}
                        <li>
                            <a href="{% url 'vehicle:index' %}?page={{ page_object.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_index in page_range %}
                        {% ifequal page_index page_object.number %}
                            <li class="active"><a
                                    href="{% url 'vehicle:index' %}?page={{ page_index }}">{{ page_index }}</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'vehicle:index' %}?page={{ page_index }}">{{ page_index }}</a></li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_object.has_next %}
                        <li>
                            <a href="{% url 'vehicle:index' %}?page={{ page_object.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </form>
{% endblock %}

{% block footer %}
    {% ifequal user.is_super True %}
        <footer>
            <a href="{% url 'user:home_super' %}">
                <dl>
                    <dt>
                        <span class="glyphicon glyphicon-th-large"></span>
                    </dt>
                    <dd>首页</dd>
                </dl>
            </a>
            <a href="{% url 'vehicle:index' %}">
                <dl>
                    <dt>
                        <span class="glyphicon glyphicon-road"></span>
                    </dt>
                    <dd>车辆</dd>
                </dl>
            </a>
            <a href="{% url 'user:mine_super' %}">
                <dl>
                    <dt>
                        <span class="glyphicon glyphicon-home"></span>
                    </dt>
                    <dd>我的</dd>
                </dl>
            </a>
            </dl>
        </footer>
    {% else %}
        {{ block.super }}
    {% endifequal %}
{% endblock %}