User/urls.py
from django.urls import path

from User import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('homesuper/', views.home_super, name='home_super'),

    path('mine/', views.mine, name='mine'),
    path('minesuper/', views.mine_super, name='mine_super'),
    path('delete/', views.delete, name='delete'),
    path('addition/', views.addition, name='addition'),
    path('search/', views.search, name='search'),
    path('update/', views.update, name='update'),

    path('checkuser/', views.check_user, name='check_user'),
    path('activate/', views.activate, name='activate'),
    path('activatesuper/', views.activate_super, name='activate_super'),
    path('register/', views.register, name='register'),

    # 验证码
    path('getcode/', views.get_code, name='get_code'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

Vehicle/urls.py
from django.urls import path

from Vehicle import views

urlpatterns = [
    path('index/', views.index, name='index'),

    path('search/', views.search, name='search'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('add/', views.add, name='add'),
    path('checkplate/', views.check_plate, name='check_plate'),

    path('addroad/', views.add_road, name='add_road'),
    path('updateroad/', views.update_road, name='update_road'),
    path('saveroad/', views.save_road, name='save_road'),
    path('deleteroad/', views.delete_road, name='delete_road'),
    path('predict/', views.predict, name='predict'),
]

djangoGraduationProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('User.urls', 'user'), namespace='user')),
    path('vehicle/', include(('Vehicle.urls', 'vehicle'), namespace='vehicle')),
]

templates/road/add.html
{% extends 'main/vehicle_index.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--添加车牌</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:add_road' %}">vehicle_add_road</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:add_road' %}" method="post" enctype="multipart/form-data">
        <table border="1" class="table table-hover">
            <tr>
                <td><label for="road_name_input">道路名：</label></td>
                <td><input type="text" id="road_name_input" name="road_name" placeholder="请输入道路名"></td>
            </tr>
            <tr>
                <td><label for="restriction_input">道路限制：</label></td>
                <td>
                    <textarea name="restriction" id="restriction_input" cols="30" rows="3"></textarea>
                </td>
            </tr>
        </table>
        <div align="center">
            <button type="submit" class="btn btn-danger btn-lg">增加道路</button>
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">取消</button>
        </div>
    </form>
{% endblock %}

{% block footer %}

{% endblock %}

templates/road/save.html
{% extends 'main/vehicle_index.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--修改道路</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:update_road' %}">vehicle_update_road</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:save_road' %}">save</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:save_road' %}" method="post" enctype="multipart/form-data">
        <table border="1" class="table table-hover">
            <tr>
                <td><label for="road_name_input">道路名：</label></td>
                <td><input type="text" id="road_name_input" name="road_name" placeholder="{{ r_name }}"></td>
            </tr>
            <tr>
                <td><label for="restriction_input">道路限制：</label></td>
                <td>
                    <textarea name="restriction" id="restriction_input" cols="30" rows="3"></textarea>
                </td>
            </tr>
        </table>
        <div align="center">
            <button type="submit" class="btn btn-danger btn-lg">保存修改</button>
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">取消</button>
        </div>
    </form>
{% endblock %}

{% block footer %}

{% endblock %}

templates/road/update.html
{% extends 'base_main.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/vehicle/css/index.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/road/js/update.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--更新道路</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:update_road' %}">vehicle_update_road</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:update_road' %}" method="get">

        <table border="1" class="table table-hover">
            <tr class="active">
                <td>道路</td>
                <td>限制</td>
                <td>修改</td>
                <td>删除</td>
            </tr>
            {% for road in page_object.object_list %}
                {#            未删除的显示出来#}
                {% ifequal road.r_is_delete False %}
                    <tr>
                        <td>{{ road.r_name }}</td>
                        <td>{{ road.r_restriction }}</td>
                        <td><a href="{% url 'vehicle:save_road' %}?road_id={{ road.id }}">修改</a></td>
                        <td><a href="{% url 'vehicle:delete_road' %}?road_id={{ road.id }}">删除</a></td>
                    </tr>
                {% endifequal %}
            {% endfor %}
        </table>
        <div align="center">
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">返回</button>
        </div>
        {#    分页器#}
        <div align="center">
            <nav aria-label="Page navigation">
                <ul class="pagination pagination-lg">
                    {% if page_object.has_previous %}
                        <li>
                            <a href="{% url 'vehicle:index' %}?page={{ page_object.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_index in page_range %}
                        {% ifequal page_index page_object.number %}
                            <li class="active"><a
                                    href="{% url 'vehicle:index' %}?page={{ page_index }}">{{ page_index }}</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'vehicle:index' %}?page={{ page_index }}">{{ page_index }}</a></li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_object.has_next %}
                        <li>
                            <a href="{% url 'vehicle:index' %}?page={{ page_object.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

    </form>
{% endblock %}