User/urls.py
from django.urls import path

from User import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('homesuper/', views.home_super, name='home_super'),

    path('mine/', views.mine, name='mine'),
    path('minesuper/', views.mine_super, name='mine_super'),
    path('delete/', views.delete, name='delete'),
    path('addition/', views.addition, name='addition'),
    path('search/', views.search, name='search'),
    path('update/', views.update, name='update'),

    path('checkuser/', views.check_user, name='check_user'),
    path('activate/', views.activate, name='activate'),
    path('activatesuper/', views.activate_super, name='activate_super'),
    path('register/', views.register, name='register'),

    # 验证码
    path('getcode/', views.get_code, name='get_code'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

Vehicle/urls.py
from django.urls import path

from Vehicle import views

urlpatterns = [
    path('index/', views.index, name='index'),

    path('search/', views.search, name='search'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('add/', views.add, name='add'),
    path('checkplate/', views.check_plate, name='check_plate'),

    path('addroad/', views.add_road, name='add_road'),
    path('updateroad/', views.update_road, name='update_road'),
    path('saveroad/', views.save_road, name='save_road'),
    path('deleteroad/', views.delete_road, name='delete_road'),
    path('predict/', views.predict, name='predict'),
]

djangoGraduationProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('User.urls', 'user'), namespace='user')),
    path('vehicle/', include(('Vehicle.urls', 'vehicle'), namespace='vehicle')),
]

Vehicle/models.py
from django.db import models

from User.models import User


class Road(models.Model):
    # 道路名字
    r_name = models.CharField(max_length=255, unique=True)
    # 道路限制
    r_restriction = models.CharField(max_length=511)
    # 逻辑删除 默认不删除
    r_is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'gp_road'


class Plate(models.Model):
    # 车牌号码
    p_plate = models.CharField(max_length=32)
    # 外键关联道路
    p_roads = models.ForeignKey(Road, on_delete=models.CASCADE)
    # 外键关联用户,1:M,一个车牌只属于一个用户
    p_username = models.ForeignKey(User, on_delete=models.CASCADE)
    # 记录车牌当前时间，后续用于判断是否违规
    p_time = models.DateTimeField(auto_now=True)
    # 是否违规 默认不违规
    p_against = models.BooleanField(default=False)
    # 逻辑删除 默认不删除
    p_is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'gp_plate'

Vehicle/views.py
import os

from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from User.models import User
from Vehicle.models import Plate, Road
from Vehicle.views_constant import PLATE_EXIST, PLATE_NOT_EXIST
from VehicleRecognition.surface import Surface, close_window
from Vehicle.views_utils import str_to_datetime, str_to_road_id, str_to_user_id
from djangoGraduationProject import settings
import tkinter as tk


def index(request):
    # TODO 1.分页器 2. footer判断是否是管理员 3.展示表格内容
    # 分页
    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 5))

    plates = Plate.objects.all()

    paginator = Paginator(plates, per_page)

    page_object = paginator.page(page)

    user_id = request.session.get('user_id')

    data = {
        "title": "车辆识别主页",
        'is_super': False,
        'plates': plates,
        "page_object": page_object,
        "page_range": paginator.page_range,
    }

    if user_id:  # type(user_id) is int
        user = User.objects.get(pk=user_id)
        data['user'] = user
    else:
        return render(request, 'base_vehicle.html')

    return render(request, 'main/vehicle_index.html', data)


def search(request):
    data = {
        "title": '查找用户',
        "msg": 'search success',
        'is_super': False,
    }
    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 5))

    username = request.GET.get('username')
    if len(username) == 0:
        return redirect(reverse('vehicle:index'))

    user_id = request.session.get('user_id')
    if User.objects.get(pk=user_id).is_super:
        data['is_super'] = True

    user = User.objects.filter(u_username=username).first()
    if user is None:
        data['msg'] = 'search user is not exist'
        return render(request, 'vehicle/search.html', data)
    elif user.is_delete:
        data['msg'] = 'search user is delete'
        return render(request, 'vehicle/search.html', data)

    plates = user.plate_set.all()

    paginator = Paginator(plates, per_page)

    page_object = paginator.page(page)

    data['plates'] = plates
    data['page_object'] = page_object
    data['page_range'] = paginator.page_range

    return render(request, 'vehicle/search.html', context=data)


def delete(request):
    plate_id = request.GET.get('plate_id')
    plate = Plate.objects.get(pk=plate_id)
    plate.p_is_delete = True
    plate.save()
    return redirect(reverse('vehicle:index'))


def update(request):
    if request.method == "GET":
        plate_id = request.GET.get('plate_id')
        request.session["update_plate_id"] = plate_id
        plate = Plate.objects.get(pk=plate_id)
        roads = Road.objects.all()
        data = {
            "title": "修改车牌信息",
            "plate": plate,
            "roads": roads,
        }
        return render(request, 'vehicle/update.html', context=data)
    elif request.method == "POST":
        plate_id = request.session.get("update_plate_id")

        road_str = request.POST.get("road")
        # 把str:road_name返回对应id
        p_road_id = str_to_road_id(road_str)
        date_str = request.POST.get("date")
        # 自定义函数str_to_datetime，str返回datetime.datetime
        p_time = str_to_datetime(date_str)
        against = request.POST.get("against")
        if against == 'T':
            p_against = True
        elif against == 'F':
            p_against = False
        Plate.objects.filter(pk=plate_id).update(p_roads_id=p_road_id)
        Plate.objects.filter(pk=plate_id).update(p_time=p_time)
        Plate.objects.filter(pk=plate_id).update(p_against=p_against)

    return redirect(reverse('vehicle:index'))


def add(request):
    if request.method == "GET":
        users = User.objects.all()
        roads = Road.objects.all()
        data = {
            "title": "添加车牌信息",
            "method": "GET",
            "users": users,
            "roads": roads,
        }
        return render(request, 'vehicle/add.html', context=data)
    elif request.method == "POST":
        pic = request.FILES.get('pic')

        filePath = os.path.join(settings.MEDIA_ROOT, 'vehicle', pic.name)  # TODO 图片保存路径在Vehicle下面？
        print(filePath)
        with open(filePath, 'wb') as fp:
            for part in pic.chunks():
                fp.write(part)
                fp.flush()

        p_name = request.POST.get('p_name')
        username_str = request.POST.get('username')
        # 把str:username_str返回对应id
        p_username_id = str_to_user_id(username_str)
        road_str = request.POST.get("road")
        # 把str:road_name返回对应id
        p_road_id = str_to_road_id(road_str)
        date_str = request.POST.get('date')
        # 自定义函数str_to_datetime，str返回datetime.datetime
        p_time = str_to_datetime(date_str)
        against = request.POST.get('against')
        if against == 'T':
            p_against = True
        elif against == 'F':
            p_against = False

        plate = Plate()
        plate.p_plate = p_name
        plate.p_username_id = p_username_id
        plate.p_roads_id = p_road_id
        plate.p_time = p_time
        plate.p_against = p_against
        plate.save()

        return redirect(reverse('vehicle:index'))


def add_road(request):
    if request.method == 'GET':
        data = {
            "title": '添加道路',
        }
        return render(request, 'road/add.html', context=data)
    elif request.method == 'POST':
        r_name = request.POST.get('road_name')
        restriction = request.POST.get('restriction')
        road = Road()
        road.r_name = r_name
        road.r_restriction = restriction
        road.r_is_delete = False
        road.save()
    return redirect(reverse('vehicle:index'))


def update_road(request):
    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 5))

    roads = Road.objects.all()

    paginator = Paginator(roads, per_page)

    page_object = paginator.page(page)

    data = {
        "title": "更新道路",
        'roads': roads,
        "page_object": page_object,
        "page_range": paginator.page_range,
    }

    return render(request, 'road/update.html', data)


def save_road(request):
    if request.method == 'GET':
        rid = request.GET.get('road_id')
        request.session["save_road_id"] = rid
        r_name = Road.objects.get(pk=rid).r_name
        data = {
            "title": "保存道路",
            "r_name": r_name,
        }
        return render(request, 'road/save.html', data)
    elif request.method == 'POST':
        rid = request.session.get('save_road_id')
        r_name = request.POST.get('road_name')
        r_restriction = request.POST.get('restriction')
        road = Road.objects.get(pk=rid)
        road.r_name = r_name
        road.r_restriction = r_restriction
        road.save()
    return redirect(reverse('vehicle:update_road'))


def delete_road(request):
    r_id = request.GET.get('road_id')
    road = Road.objects.get(pk=r_id)
    road.r_is_delete = True
    road.save()
    return redirect(reverse('vehicle:update_road'))


def predict(request):
    win = tk.Tk()
    surface = Surface(win)
    win.protocol('WM_DELETE_WINDOW', close_window)
    win.mainloop()
    return HttpResponse('h')


def check_plate(request):
    p_plate = request.GET.get('plate')
    plate = Plate.objects.filter(p_plate=p_plate).first()
    data = {
        "status": PLATE_EXIST,
        "msg": 'plate existed',
    }
    if isinstance(plate, type(None)):
        u = []
        data['status'] = PLATE_NOT_EXIST
        data['msg'] = 'plate not exist'
        users = User.objects.all()
        for user in users:
            u.append(user.u_username)
        data['username'] = u
        return JsonResponse(data)
    username = plate.p_username.u_username
    uid = plate.p_username_id
    data['username'] = username
    data['uid'] = uid
    return JsonResponse(data)

templates/vehicle/add.html
{% extends 'main/vehicle_index.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/vehicle/js/add.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--添加车牌</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:add' %}">vehicle_add</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:add' %}" method="post" enctype="multipart/form-data">
        <table border="1" class="table table-hover">
            {% ifequal method 'GET' %}
                <tr>
                    <td><label for="pic_input">上传：</label></td>
                    <td><input name="pic" type="file" id="pic_input"></td>
                </tr>
                <tr>
                    <td><label for="p_name">车牌：</label></td>
                    <td><input name="p_name" id="p_name" type="text"><span id="pname_info"></span></td>
                </tr>
                <tr>
                    <td><label>用户名：</label></td>
                    <td><select name="username" id="username_select">
                        {% for user in users %}
                            <option>{{ user.u_username }}</option>
                        {% endfor %}
                    </select><span id="username_info"></span></td>
                </tr>
                <tr>
                    <td><label>道路名：</label></td>
                    <td>
                        <select name="road" id="road_select">
                            {% for road in roads %}
                                <option>{{ road.r_name }} {{ road.r_restriction }}</option>
                            {% endfor %}
                        </select>
                    <span id="restriction_info"></span>
{#                    # TODO 道路限制提示#}
                    </td>
                </tr>
                <tr>
                    <td><label for="date">通行时间：</label></td>
                    <td><input name="date" id="date" type="datetime-local"></td>
                </tr>
                <tr>
                    <td><label for="against_input">是否违规：</label></td>
                    <td>
                        <label><input name="against" value="T" type="radio">违规</label>
                        <label><input name="against" value="F" type="radio">未违规</label>
                    </td>
                </tr>
            {% endifequal %}
        </table>
        <div align="center">
            <button type="submit" class="btn btn-danger btn-lg">上传</button>
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">取消</button>
        </div>
    </form>

{% endblock %}

{% block footer %}

{% endblock %}

templates/vehicle/search.html
{% extends 'main/vehicle_index.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--查找车牌</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:search' %}">search</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}

    <div align="center">
        <span>Tip:</span>
        <label for="search" class="control-label">{{ msg }}</label>
        <a class="btn btn-default btn-lg" href="{% url 'vehicle:index' %}">返回</a>
    </div>
    {% ifequal msg "search success" %}
        <table border="1" class="table table-hover">
            <tr class="active">
                <td>姓名</td>
                <td>车牌</td>
                <td>道路</td>
                <td>道路限制</td>
                <td>时间</td>
                <td>是否违规</td>
                {% ifequal is_super True %}
                    <td>删除</td>
                    <td>修改</td>
                {% endifequal %}
            </tr>

            {% for plate in page_object.object_list %}
                {% ifequal plate.p_is_delete False %}
                    <tr>
                        <td>{{ plate.p_username.u_username }}</td>
                        <td>{{ plate.p_plate }}</td>
                        <td>{{ plate.p_roads.r_name }}</td>
                        <td>{{ plate.p_roads.r_restriction }}</td>
                        <td>{{ plate.p_time }}</td>
                        {% ifequal plate.p_against False %}
                            <td>未违规</td>
                        {% else %}
                            <td>违规</td>
                        {% endifequal %}
                        {% ifequal is_super True %}
                            <td><a href="{% url 'vehicle:delete' %}?plate_id={{ plate.id }}">删除</a></td>
                            <td><a href="{% url 'vehicle:update' %}?plate_id={{ plate.id }}">修改</a>
                            </td>
                        {% endifequal %}
                    </tr>
                {% endifequal %}
            {% endfor %}
        </table>
    {% else %}
        <div align="center">
            <span>用户名错误，请返回</span>
        </div>
    {% endifequal %}

{% endblock %}

templates/vehicle/update.html
{% extends 'main/vehicle_index.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--更新车辆</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vehicle:index' %}">vehicle_index</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:search' %}">search</a></li>
            <li class="breadcrumb-item"><a href="{% url 'vehicle:update' %}">update</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'vehicle:update' %}" method="post" enctype="multipart/form-data">
        <table border="1" class="table table-hover">
            <tr>
                <td><label for="plate_input">车牌号：</label></td>
                <td>{{ plate.p_plate }}</td>
            </tr>
            <tr>
                <td><label>道路名：</label></td>
                <td>
                    <select name="road">
                        {% for road in roads %}
                            {% ifequal plate.p_roads.r_name road.r_name %}
                                <option selected>{{ road.r_name }}</option>
                            {% else %}
                                <option>{{ road.r_name }}</option>
                            {% endifequal %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="date">通行时间：</label></td>
                <td><input name="date" id="date" type="datetime-local"></td>
            </tr>
            <tr>
                <td><label for="against_input">是否违规：</label></td>
                <td>
                    <label><input type="radio" name="against" value="T">违规</label>
                    <label><input type="radio" name="against" value="F">未违规</label>
                </td>
            </tr>
        </table>
        <div align="center">
            <button type="submit" class="btn btn-danger btn-lg">保存</button>
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">取消</button>
        </div>
    </form>

{% endblock %}

{% block footer %}

{% endblock %}