User/urls.py
from django.urls import path

from User import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('homesuper/', views.home_super, name='home_super'),

    path('mine/', views.mine, name='mine'),
    path('minesuper/', views.mine_super, name='mine_super'),
    path('delete/', views.delete, name='delete'),
    path('addition/', views.addition, name='addition'),
    path('search/', views.search, name='search'),
    path('update/', views.update, name='update'),

    path('checkuser/', views.check_user, name='check_user'),
    path('activate/', views.activate, name='activate'),
    path('activatesuper/', views.activate_super, name='activate_super'),
    path('register/', views.register, name='register'),

    # 验证码
    path('getcode/', views.get_code, name='get_code'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

djangoGraduationProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('User.urls', 'user'), namespace='user')),
    path('vehicle/', include(('Vehicle.urls', 'vehicle'), namespace='vehicle')),
]

User/models.py
from django.db import models


class User(models.Model):
    u_username = models.CharField(max_length=12, unique=True)
    u_password = models.CharField(max_length=255)
    # u_email = models.CharField(max_length=64)
    u_email = models.EmailField(max_length=75)
    u_icon = models.ImageField(upload_to='icons/%Y%m%d')
    # 默认未激活
    is_active = models.BooleanField(default=False)
    # 默认不删除(存在)
    is_delete = models.BooleanField(default=False)
    # 默认是普通用户
    is_super = models.BooleanField(default=False)

    class Meta:
        db_table = 'gp_user'

User/views.py
import os
import random
import uuid
from datetime import datetime
from io import BytesIO

from PIL import Image, ImageFont
from PIL.ImageDraw import ImageDraw
from django.contrib.auth.hashers import check_password, make_password
from django.core.cache import cache
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from User.models import User
from User.views_constant import HTTP_OK, HTTP_USER_EXIST
from User.views_utils import get_color, generate_code, send_email_activate
from djangoGraduationProject import settings
from djangoGraduationProject.settings import MEDIA_KEY_PREFIX


def home(request):
    data = {
        "title": "首页",
    }
    return render(request, 'base_main.html', context=data)


def home_super(request):
    data = {
        "title": "管理员首页",
    }
    return render(request, 'main/super_index.html', context=data)


def mine(request):
    user_id = request.session.get('user_id')
    data = {
        "title": "个人中心",
        'is_login': False,
        'user_id': user_id,
    }

    if user_id:
        user = User.objects.get(pk=user_id)
        data['is_login'] = True
        data['username'] = user.u_username
        data['icon'] = MEDIA_KEY_PREFIX + user.u_icon.url

    return render(request, 'main/mine.html', context=data)


def mine_super(request):
    # 分页
    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 5))

    users = User.objects.all()

    paginator = Paginator(users, per_page)

    page_object = paginator.page(page)

    user_id = request.session.get('user_id')

    data = {
        "title": "管理员中心",
        'is_login': False,
        'users': users,
        "page_object": page_object,
        "page_range": paginator.page_range
    }

    if user_id:
        user = User.objects.get(pk=user_id)
        data['is_login'] = True
        data['username'] = user.u_username
        data['icon'] = MEDIA_KEY_PREFIX + user.u_icon.url

    return render(request, 'main/mine_super.html', context=data)


# 获取验证码
def get_code(request):
    # 初始化画布，初始化画笔

    mode = "RGB"
    size = (200, 100)
    red = get_color()
    green = get_color()
    blue = get_color()
    color_bg = (red, green, blue)
    image = Image.new(mode=mode, size=size, color=color_bg)
    image_draw = ImageDraw(image, mode=mode)
    image_font = ImageFont.truetype(settings.FONT_PATH, 100)
    verify_code = generate_code()
    request.session['verify_code'] = verify_code

    for i in range(4):
        fill = (get_color(), get_color(), get_color())
        image_draw.text(xy=(50 * i, 0), text=verify_code[i], font=image_font, fill=fill)
    for i in range(2000):
        fill = (get_color(), get_color(), get_color())
        xy = (random.randrange(201), random.randrange(100))
        image_draw.point(xy, fill)

    fp = BytesIO()
    image.save(fp, "png")
    return HttpResponse(fp.getvalue(), content_type="image/png")


def register(request):
    if request.method == "GET":
        data = {
            "title": "注册",
        }
        return render(request, 'user/register.html', context=data)
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        # password = hash_str(password)，views.utils模块中的hash_str返回sha512加密
        password = make_password(password)
        email = request.POST.get("email")
        icon = request.FILES.get("icon")

        user = User()
        user.u_username = username
        user.u_password = password
        user.u_email = email
        user.u_icon = icon
        user.save()

        u_token = uuid.uuid4().hex

        cache.set(u_token, user.id, timeout=60 * 60 * 24)

        send_email_activate(username, email, u_token)

        return redirect(reverse("user:login"))


def login(request):
    if request.method == "GET":
        error_message = request.session.get('error_message')
        data = {
            "title": "登录",
        }
        if error_message:
            del request.session['error_message']
            data['error_message'] = error_message
        return render(request, 'user/login.html', context=data)
    elif request.method == "POST":
        # 验证码校验
        receive_code = request.POST.get("verify_code")
        store_code = request.session.get("verify_code")

        if receive_code.lower() != store_code.lower():
            request.session['error_message'] = 'verify code error'
            return redirect(reverse('user:login'))

        # 内聚校验方式，检验用户名、密码是否在库中
        username = request.POST.get("username")
        password = request.POST.get("password")

        # 账号被删除后，必须要管理员找回
        users = User.objects.filter(u_username=username).filter(is_delete=False)

        if users.exists():
            user = users.first()

            if check_password(password, user.u_password):

                if user.is_active:
                    request.session['user_id'] = int(user.id)

                    if user.is_super:
                        return redirect(reverse('user:mine_super'))

                    return redirect(reverse('user:mine'))
                else:
                    # print('用户未激活')
                    request.session['error_message'] = 'user not activate'
                    # TODO 未激活重定向activate_fail.html
                    return redirect(reverse('user:login'))
            else:
                # print("密码错误")
                request.session['error_message'] = 'password error'
                return redirect(reverse('user:login'))
        # print("用户不存在")
        request.session['error_message'] = 'user does not exist'
        return redirect(reverse('user:login'))


def logout(request):
    request.session.flush()

    return redirect(reverse('user:mine'))


# 服务器校验方式，注册时，检查用户名是否重复
def check_user(request):
    username = request.GET.get("username")

    users = User.objects.filter(u_username=username)

    data = {
        "status": HTTP_OK,
        "msg": 'user can use',
    }

    if users.exists():
        data['status'] = HTTP_USER_EXIST
        data['msg'] = 'user already exist'
    else:
        pass

    return JsonResponse(data=data)


def activate(request):
    u_token = request.GET.get('u_token')  # 激活时，url中传递u_token用GET获取

    user_id = cache.get(u_token)

    if user_id:
        cache.delete(u_token)

        user = User.objects.get(pk=user_id)

        user.is_active = True

        user.save()
        return redirect(reverse('user:login'))

    return render(request, 'user/activate_fail.html')


# 管理员删除用户
def delete(request):
    user_id = request.GET.get('user_id')
    user = User.objects.get(pk=user_id)
    user.is_delete = True
    user.is_active = False
    user.save()
    for plate in user.plate_set.all():
        # print(plate.p_plate)
        plate.p_is_delete = True
        plate.save()
    return redirect(reverse('user:mine_super'))


# 管理员恢复用户
def addition(request):
    user_id = request.GET.get('user_id')
    user = User.objects.get(pk=user_id)
    user.is_delete = False
    user.save()
    for plate in user.plate_set.all():
        # print(plate.p_plate)
        plate.p_is_delete = False
        plate.save()
    return redirect(reverse('user:mine_super'))


def search(request):
    username = request.GET.get('username')
    if username is None:
        return redirect(reverse('user:mine_super'))

    user = User.objects.filter(u_username=username).first()
    data = {
        "title": '查找用户',
        "msg": 'search success',
    }
    # print(user)
    # print(type(user))
    if user:
        data['user_id'] = user.id
        data['username'] = user.u_username
        data['email'] = user.u_email
        data['activate'] = user.is_active
        data['delete'] = user.is_delete
    else:
        data['msg'] = 'search user is not exist'
    return render(request, 'user/search.html', context=data)


def update(request):
    if request.method == "GET":
        user_id = request.GET.get('user_id')
        data = {
            "title": "修改信息",
            "u_state": True,
        }
        if len(user_id) == 0:
            user_id = request.session.get('user_id')
            data['u_state'] = False
        request.session["update_user_id"] = user_id

        return render(request, 'user/update.html', context=data)
    elif request.method == "POST":
        user_id = request.session.get("update_user_id")

        username = request.POST.get("username")
        password = request.POST.get("password")
        password = make_password(password)
        email = request.POST.get("email")
        icon = request.FILES.get("icon")

        user = User.objects.get(pk=user_id)
        u_icon_name =user.u_icon.name
        u_icon_re = u_icon_name.split('/')[-1]
        f_name = u_icon_name[0:len(u_icon_name)-len(u_icon_re)-1]
        filePath = os.path.join(settings.MEDIA_ROOT, f_name, icon.name)
        # print(filePath)
        with open(filePath, 'wb') as fp:
            for part in icon.chunks():
                fp.write(part)
                fp.flush()
        # user = User.objects.get(pk=user_id)
        # user.u_username = username
        # user.u_password = password
        # user.u_email = email
        # user.u_icon = icon

        if username != '':
            User.objects.filter(pk=user_id).update(u_username=username)
        if password != '':
            User.objects.filter(pk=user_id).update(u_password=password)
        if email != '':
            User.objects.filter(pk=user_id).update(u_email=email)
        if icon is not None:
            user.u_icon.name = user.u_icon.name.replace(u_icon_re, icon.name)
            user.save()

    return redirect(reverse('user:mine_super'))


def activate_super(request):
    uid = request.GET.get('user_id')
    user = User.objects.get(pk=uid)
    user.is_active = True
    user.save()
    return redirect(reverse('user:mine_super'))

templates/user/activate.html
<h4>Dear {{ username }}</h4>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎注册深度学习车辆识别系统，但您的账号没有进行激活认证，请点击下面的激活按钮进行激活</p>

<a href="{{ activate_url }}">激活</a>
<p>如上面的激活按钮不可用，请将下面的地址复制到浏览器进行激活</p>
<p>{{ activate_url }}</p>
<h5>Best Wishes</h5>
<p>From GraduationProject</p>

templates/user/activate_fail.html
{% extends 'base_user.html' %}

{% block content %}
    <div>
        <h3>激活失败，请重新申请激活</h3>
    </div>
{% endblock %}

templates/user/login.html
{% extends 'base_user.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/user/css/login.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/user/js/login.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--登录</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine' %}">mine</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:login' %}">login</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'user:login' %}" onsubmit="parse_data()">

            {% csrf_token %}

            <p>{{ error_message }}</p>

            <div class="form-group">
                <label for="username_input">用户名：</label>
                <input name="username" type="text" class="form-control" id="username_input" placeholder="用户名">
            </div>

            <div class="form-group">
                <label for="password_input">密码：</label>
                <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
            </div>
            <div class="form-group">
                <label for="verify_code_input">验证码：</label>
                <input name="verify_code" type="text" class="form-control" id="verify_code_input" placeholder="请输入验证码">
                <img src="{% url 'user:get_code' %}" alt="verify_code">
            </div>
            <button type="submit" class="btn btn-success btn-lg">登录</button>
            <a class="btn btn-default btn-lg" href="{% url 'user:mine_super' %}">返回</a>
        </form>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base_user.html' %}

{% load static %}

{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'base/user/css/register.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'base/user/js/register.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
    <p>毕业设计--注册</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine' %}">mine</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:register' %}">register</a></li></ul>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data" action="{% url 'user:register' %}" onsubmit="return check()">

            {% csrf_token %}

            <div class="form-group">
                <label for="username_input">用户名：</label>
                <input name="username" type="text" class="form-control" id="username_input" placeholder="请输入用户名">
                <span id="username_info"></span>
            </div>

            <div class="form-group">
                <label for="password_input">密码：</label>
                <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
                <span id="password_tip"></span>
            </div>
            <div class="form-group">
                <label for="password_confirm_input">确认密码：</label>
                <input type="password" class="form-control" id="password_confirm_input" placeholder="请再次输入密码">
                <span id="password_info"></span>
            </div>

             <div class="form-group">
                <label for="email_input">邮箱：</label>
                <input name="email" type="email" class="form-control" id="email_input" placeholder="请输入邮箱">
                 <span id="email_info"></span>
            </div>

            <div class="form-group">
                <label for="icon_input">头像</label>
                <input name="icon" type="file" id="icon_input">
            </div>

            <button type="submit" class="btn btn-success ">注册</button>

        <a class="btn btn-default btn-lg" href="{% url 'user:mine_super' %}">返回</a>
        </form>
    </div>
{% endblock %}

templates/user/search.html
{% extends 'main/mine.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--查找用户</p>
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine_super' %}">mine_super</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:search' %}">search</a></li>
        </ul>
    </header>
{% endblock %}

{% block content %}
    <div align="center">
        <span>tip:</span>
        <label for="search" class="control-label">{{ msg }}</label>
        <a class="btn btn-default btn-lg" href="{% url 'user:mine_super' %}">返回</a>
    </div>
    {% ifequal msg "search success" %}
        <table border="1" class="table table-hover">
            <tr class="active">
                <td>姓名</td>
                <td>邮箱</td>
                <td>激活状态</td>
                <td>是否删除</td>
                {% ifequal delete False %}
                <td>删除用户</td>
                {% else %}
                    <td>恢复用户</td>
                {% endifequal %}
                <td>修改信息</td>
            </tr>

            <tr>
                <td>{{ username }}</td>
                <td>{{ email }}</td>
                {% ifequal activate False %}
                    <td><a href="{% url 'user:activate_super' %}?user_id={{ user_id }}">未激活(点击激活)</a></td>
                {% else %}
                    <td>已激活</td>
                {% endifequal %}
                {% ifequal delete False %}
                    <td>账号正常</td>
                    <td><a href="{% url 'user:delete' %}?user_id={{ user_id }}">删除</a></td>
                {% else %}
                    <td>账号已删除</td>
                    <td><a href="{% url 'user:addition' %}?user_id={{ user_id }}">恢复</a></td>
                {% endifequal %}
                <td><a href="{% url 'user:update' %}?user_id={{ user_id }}">修改</a></td>
            </tr>
        </table>
    {% else %}
        <span>用户名错误，请返回</span>
    {% endifequal %}

{% endblock %}

{% block footer %}

{% endblock %}

templates/user/update.html
{% extends 'main/mine.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/user/js/update.js' %}"></script>
{% endblock %}

{% block header %}
    <header>
        <p>毕业设计--修改用户信息</p>
        {% ifequal u_state True %}
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine_super' %}">mine_super</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:search' %}">search</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:update' %}">update</a></li>
        </ul>
            {% else %}
            <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'user:mine' %}">mine</a></li>
            <li class="breadcrumb-item"><a href="{% url 'user:update' %}">update</a></li>
        </ul>
        {% endifequal %}
    </header>
{% endblock %}

{% block content %}
    <form action="{% url 'user:update' %}" method="post" enctype="multipart/form-data" onsubmit="return check()">
        <table border="1" class="table table-hover">
            <tr>
                <td><label for="username_input">用户名：</label></td>
                <td><input name="username" id="username_input" type="text" placeholder="请输入用户名">
                    <span id="username_info"></span></td>
            </tr>
            <tr>
                <td><label for="password_input">密码：</label></td>
                <td><input name="password" id="password_input" type="password" placeholder="不输入维持原密码">
                    <span id="password_info"></span></td>
            </tr>
            <tr>
                <td><label for="email_input">邮箱：</label></td>
                <td><input name="email" id="email_input" type="email" placeholder="不输入维持原邮箱">
                    <span id="email_info"></span></td>
            </tr>
            <tr>
                <td><label for="icon_input">头像</label></td>
                <td><input name="icon" type="file" id="icon_input"></td>
            </tr>
        </table>
        <div align="center">
            <button type="submit" class="btn btn-danger btn-lg">保存</button>
            <button onclick="javascript:history.go(-1);" type="reset" class="btn btn-default btn-lg">取消</button>
        </div>
    </form>

{% endblock %}

{% block footer %}

{% endblock %}